---
title: "R Notebook"
output: github_document
---

```{r}
library("dada2")
```


```{r}
install.packages("Rcpp")
```
```{r}
```


```{r}
path<-"/home/rstudio/happygit/tutodada2/Tutodada2/MiSeq_SOP"
list.files(path)
```


```{r}
```
```{r}

```
```{r}


```
```{r}
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
plotQualityProfile(fnFs[1:2])
```


```{r}
install.packages("BiocManager")
BiocManager::install("dada2")
library(dada2)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("dada2")


```
```{r}
path<-"/home/rstudio/happygit/tutodada2/Tutodada2/MiSeq_SOP"
list.files(path)
```
```{r}
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
plotQualityProfile(fnFs[1:2])
```

